import React from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import { AuthProvider } from './context/AuthContext'
import { CartProvider } from './context/CartContext'
import { MembershipProvider } from './context/MembershipContext'
import { WishlistProvider } from './context/WishlistContext'
import './index.css'
createRoot(document.getElementById('root')).render(<BrowserRouter><AuthProvider><MembershipProvider><WishlistProvider><CartProvider><App /></CartProvider></WishlistProvider></MembershipProvider></AuthProvider></BrowserRouter>)
